# AUTO-GENERATED by scripts/generate_models.py — do not edit manually.
# Portal: pathogen | Result type: taxon
from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field

from ena_api_handler.query import ENABaseQuery


class PathogenTaxonFields(str, Enum):
    """Returnable fields for taxon via the pathogen portal."""

    AUTHORITY = "authority"  # taxonomic authority
    COMMON_NAME = "common_name"  # Everyday name for an organism
    DESCRIPTION = "description"  # brief sequence description
    GENBANK_COMMON_NAME = (
        "genbank_common_name"  # Everyday name for an organism in GenBank
    )
    GENETIC_CODE = "genetic_code"  # Set of rules that determine sequence translation
    LINEAGE = "lineage"  # names representing hierarchical classification of an organism
    MERGED_TAX_ID = "merged_tax_id"  # Old tax ids merged to this tax id
    RANK = "rank"  # Relative level of a group of organisms in an ancestral hierarchy.
    SCIENTIFIC_NAME = "scientific_name"  # scientific name of an organism
    STATUS = "status"  # Status
    SYNONYM = "synonym"  # Synonyms for taxon
    TAG = "tag"  # Classification Tags
    TAX_DIVISION = "tax_division"  # taxonomic division
    TAX_ID = "tax_id"  # NCBI taxonomic classification
    TAX_LINEAGE = "tax_lineage"  # Complete taxonomic lineage for an organism


class PathogenTaxonQuery(ENABaseQuery):
    """Searchable fields for taxon via the pathogen portal."""

    authority: Optional[str] = Field(default=None, description="taxonomic authority")
    common_name: Optional[str] = Field(
        default=None, description="Everyday name for an organism"
    )
    description: Optional[str] = Field(
        default=None, description="brief sequence description"
    )
    genbank_common_name: Optional[str] = Field(
        default=None, description="Everyday name for an organism in GenBank"
    )
    genetic_code: Optional[str] = Field(
        default=None, description="Set of rules that determine sequence translation"
    )
    lineage: Optional[str] = Field(
        default=None,
        description="names representing hierarchical classification of an organism ",
    )
    rank: Optional[str] = Field(
        default=None,
        description="Relative level of a group of organisms in an ancestral hierarchy.",
    )
    scientific_name: Optional[str] = Field(
        default=None, description="scientific name of an organism"
    )
    status: Optional[str] = Field(default=None, description="Status")
    synonym: Optional[str] = Field(default=None, description="Synonyms for taxon")
    tag: Optional[str] = Field(default=None, description="Classification Tags")
    tax_division: Optional[str] = Field(default=None, description="taxonomic division")
    tax_id: Optional[str] = Field(
        default=None, description="NCBI taxonomic classification"
    )


class PathogenTaxonResult(BaseModel):
    """Typed result row for taxon via the pathogen portal."""

    model_config = ConfigDict(extra="allow")

    authority: Optional[str] = Field(default=None, description="taxonomic authority")
    common_name: Optional[str] = Field(
        default=None, description="Everyday name for an organism"
    )
    description: Optional[str] = Field(
        default=None, description="brief sequence description"
    )
    genbank_common_name: Optional[str] = Field(
        default=None, description="Everyday name for an organism in GenBank"
    )
    genetic_code: Optional[str] = Field(
        default=None, description="Set of rules that determine sequence translation"
    )
    lineage: Optional[str] = Field(
        default=None,
        description="names representing hierarchical classification of an organism ",
    )
    merged_tax_id: Optional[str] = Field(
        default=None, description="Old tax ids merged to this tax id"
    )
    rank: Optional[str] = Field(
        default=None,
        description="Relative level of a group of organisms in an ancestral hierarchy.",
    )
    scientific_name: Optional[str] = Field(
        default=None, description="scientific name of an organism"
    )
    status: Optional[str] = Field(default=None, description="Status")
    synonym: Optional[str] = Field(default=None, description="Synonyms for taxon")
    tag: Optional[str] = Field(default=None, description="Classification Tags")
    tax_division: Optional[str] = Field(default=None, description="taxonomic division")
    tax_id: Optional[str] = Field(
        default=None, description="NCBI taxonomic classification"
    )
    tax_lineage: Optional[str] = Field(
        default=None, description="Complete taxonomic lineage for an organism"
    )
