# AUTO-GENERATED by scripts/generate_models.py — do not edit manually.
from __future__ import annotations

from .analysis import FAANGAnalysisFields, FAANGAnalysisQuery, FAANGAnalysisResult
from .analysis_study import (
    FAANGAnalysisStudyFields,
    FAANGAnalysisStudyQuery,
    FAANGAnalysisStudyResult,
)
from .assembly import FAANGAssemblyFields, FAANGAssemblyQuery, FAANGAssemblyResult
from .coding import FAANGCodingFields, FAANGCodingQuery, FAANGCodingResult
from .noncoding import FAANGNoncodingFields, FAANGNoncodingQuery, FAANGNoncodingResult
from .read_experiment import (
    FAANGReadExperimentFields,
    FAANGReadExperimentQuery,
    FAANGReadExperimentResult,
)
from .read_run import FAANGReadRunFields, FAANGReadRunQuery, FAANGReadRunResult
from .read_study import FAANGReadStudyFields, FAANGReadStudyQuery, FAANGReadStudyResult
from .sample import FAANGSampleFields, FAANGSampleQuery, FAANGSampleResult
from .sequence import FAANGSequenceFields, FAANGSequenceQuery, FAANGSequenceResult
from .study import FAANGStudyFields, FAANGStudyQuery, FAANGStudyResult
from .taxon import FAANGTaxonFields, FAANGTaxonQuery, FAANGTaxonResult
from .tls_set import FAANGTlsSetFields, FAANGTlsSetQuery, FAANGTlsSetResult
from .tsa_set import FAANGTsaSetFields, FAANGTsaSetQuery, FAANGTsaSetResult
from .wgs_set import FAANGWgsSetFields, FAANGWgsSetQuery, FAANGWgsSetResult

__all__ = [
    "FAANGAnalysisFields",
    "FAANGAnalysisQuery",
    "FAANGAnalysisResult",
    "FAANGAnalysisStudyFields",
    "FAANGAnalysisStudyQuery",
    "FAANGAnalysisStudyResult",
    "FAANGAssemblyFields",
    "FAANGAssemblyQuery",
    "FAANGAssemblyResult",
    "FAANGCodingFields",
    "FAANGCodingQuery",
    "FAANGCodingResult",
    "FAANGNoncodingFields",
    "FAANGNoncodingQuery",
    "FAANGNoncodingResult",
    "FAANGReadExperimentFields",
    "FAANGReadExperimentQuery",
    "FAANGReadExperimentResult",
    "FAANGReadRunFields",
    "FAANGReadRunQuery",
    "FAANGReadRunResult",
    "FAANGReadStudyFields",
    "FAANGReadStudyQuery",
    "FAANGReadStudyResult",
    "FAANGSampleFields",
    "FAANGSampleQuery",
    "FAANGSampleResult",
    "FAANGSequenceFields",
    "FAANGSequenceQuery",
    "FAANGSequenceResult",
    "FAANGStudyFields",
    "FAANGStudyQuery",
    "FAANGStudyResult",
    "FAANGTaxonFields",
    "FAANGTaxonQuery",
    "FAANGTaxonResult",
    "FAANGTlsSetFields",
    "FAANGTlsSetQuery",
    "FAANGTlsSetResult",
    "FAANGTsaSetFields",
    "FAANGTsaSetQuery",
    "FAANGTsaSetResult",
    "FAANGWgsSetFields",
    "FAANGWgsSetQuery",
    "FAANGWgsSetResult",
]
