language: python
python:
  - "3.5"
  - "3.6"

install:
  # Test dependencies
  - pip install -r requirements-test.txt
  - pip install -U  .

script:
  - pytest --reruns 3 --reruns-delay 1

after_success:
  - pip install codacy-coverage
  - python-codacy-coverage -r coverage.xml
