# AUTO-GENERATED by scripts/generate_models.py — do not edit manually.
# Precise return-type stub for ena_api_handler.client, kept separate so the
# runtime module stays free of the generated @overload block.
from __future__ import annotations

from enum import Enum
from typing import Any, overload

import httpx
from pydantic import BaseModel

from ena_api_handler.models import (
    ENAAnalysisQuery,
    ENAAnalysisResult,
    ENAAnalysisStudyQuery,
    ENAAnalysisStudyResult,
    ENAAssemblyQuery,
    ENAAssemblyResult,
    ENACodingQuery,
    ENACodingResult,
    ENANoncodingQuery,
    ENANoncodingResult,
    ENAReadExperimentQuery,
    ENAReadExperimentResult,
    ENAReadRunQuery,
    ENAReadRunResult,
    ENAReadStudyQuery,
    ENAReadStudyResult,
    ENASampleQuery,
    ENASampleResult,
    ENASequenceQuery,
    ENASequenceResult,
    ENAStudyQuery,
    ENAStudyResult,
    ENATaxonQuery,
    ENATaxonResult,
    ENATlsSetQuery,
    ENATlsSetResult,
    ENATsaSetQuery,
    ENATsaSetResult,
    ENAWgsSetQuery,
    ENAWgsSetResult,
    FAANGAnalysisQuery,
    FAANGAnalysisResult,
    FAANGAnalysisStudyQuery,
    FAANGAnalysisStudyResult,
    FAANGAssemblyQuery,
    FAANGAssemblyResult,
    FAANGCodingQuery,
    FAANGCodingResult,
    FAANGNoncodingQuery,
    FAANGNoncodingResult,
    FAANGReadExperimentQuery,
    FAANGReadExperimentResult,
    FAANGReadRunQuery,
    FAANGReadRunResult,
    FAANGReadStudyQuery,
    FAANGReadStudyResult,
    FAANGSampleQuery,
    FAANGSampleResult,
    FAANGSequenceQuery,
    FAANGSequenceResult,
    FAANGStudyQuery,
    FAANGStudyResult,
    FAANGTaxonQuery,
    FAANGTaxonResult,
    FAANGTlsSetQuery,
    FAANGTlsSetResult,
    FAANGTsaSetQuery,
    FAANGTsaSetResult,
    FAANGWgsSetQuery,
    FAANGWgsSetResult,
    MetagenomeAnalysisQuery,
    MetagenomeAnalysisResult,
    MetagenomeAnalysisStudyQuery,
    MetagenomeAnalysisStudyResult,
    MetagenomeAssemblyQuery,
    MetagenomeAssemblyResult,
    MetagenomeCodingQuery,
    MetagenomeCodingResult,
    MetagenomeNoncodingQuery,
    MetagenomeNoncodingResult,
    MetagenomeReadExperimentQuery,
    MetagenomeReadExperimentResult,
    MetagenomeReadRunQuery,
    MetagenomeReadRunResult,
    MetagenomeReadStudyQuery,
    MetagenomeReadStudyResult,
    MetagenomeSampleQuery,
    MetagenomeSampleResult,
    MetagenomeSequenceQuery,
    MetagenomeSequenceResult,
    MetagenomeStudyQuery,
    MetagenomeStudyResult,
    MetagenomeTaxonQuery,
    MetagenomeTaxonResult,
    MetagenomeTlsSetQuery,
    MetagenomeTlsSetResult,
    MetagenomeTsaSetQuery,
    MetagenomeTsaSetResult,
    MetagenomeWgsSetQuery,
    MetagenomeWgsSetResult,
    PathogenAnalysisQuery,
    PathogenAnalysisResult,
    PathogenAnalysisStudyQuery,
    PathogenAnalysisStudyResult,
    PathogenAssemblyQuery,
    PathogenAssemblyResult,
    PathogenCodingQuery,
    PathogenCodingResult,
    PathogenNoncodingQuery,
    PathogenNoncodingResult,
    PathogenReadExperimentQuery,
    PathogenReadExperimentResult,
    PathogenReadRunQuery,
    PathogenReadRunResult,
    PathogenReadStudyQuery,
    PathogenReadStudyResult,
    PathogenSampleQuery,
    PathogenSampleResult,
    PathogenSequenceQuery,
    PathogenSequenceResult,
    PathogenStudyQuery,
    PathogenStudyResult,
    PathogenTaxonQuery,
    PathogenTaxonResult,
    PathogenTlsSetQuery,
    PathogenTlsSetResult,
    PathogenTsaSetQuery,
    PathogenTsaSetResult,
    PathogenWgsSetQuery,
    PathogenWgsSetResult,
)
from ena_api_handler.query import ENABaseQuery, ENAQueryClause
from ena_api_handler.types import ENAPortalDataPortal

class ENAClientError(Exception): ...
class ENAAvailabilityError(ENAClientError): ...

class ENAClient:
    _url: str
    _auth: httpx.BasicAuth | None
    _timeout: float
    _retries: int
    _client: httpx.Client | None
    _async_client: httpx.AsyncClient | None
    def __init__(
        self,
        url: str = ...,
        username: str | None = ...,
        password: str | None = ...,
        timeout: float = ...,
        retries: int = ...,
    ) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> ENAClient: ...
    def __exit__(self, *_: Any) -> None: ...
    async def aclose(self) -> None: ...
    async def __aenter__(self) -> ENAClient: ...
    async def __aexit__(self, *_: Any) -> None: ...
    def download_runs(self, runs: Any) -> None: ...
    @overload
    def search(
        self,
        result: Enum,
        query: ENAAnalysisQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[ENAAnalysisResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: ENAAnalysisStudyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[ENAAnalysisStudyResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: ENAAssemblyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[ENAAssemblyResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: ENACodingQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[ENACodingResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: ENANoncodingQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[ENANoncodingResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: ENAReadExperimentQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[ENAReadExperimentResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: ENAReadRunQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[ENAReadRunResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: ENAReadStudyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[ENAReadStudyResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: ENASampleQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[ENASampleResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: ENASequenceQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[ENASequenceResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: ENAStudyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[ENAStudyResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: ENATaxonQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[ENATaxonResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: ENATlsSetQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[ENATlsSetResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: ENATsaSetQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[ENATsaSetResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: ENAWgsSetQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[ENAWgsSetResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: FAANGAnalysisQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[FAANGAnalysisResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: FAANGAnalysisStudyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[FAANGAnalysisStudyResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: FAANGAssemblyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[FAANGAssemblyResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: FAANGCodingQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[FAANGCodingResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: FAANGNoncodingQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[FAANGNoncodingResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: FAANGReadExperimentQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[FAANGReadExperimentResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: FAANGReadRunQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[FAANGReadRunResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: FAANGReadStudyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[FAANGReadStudyResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: FAANGSampleQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[FAANGSampleResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: FAANGSequenceQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[FAANGSequenceResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: FAANGStudyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[FAANGStudyResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: FAANGTaxonQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[FAANGTaxonResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: FAANGTlsSetQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[FAANGTlsSetResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: FAANGTsaSetQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[FAANGTsaSetResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: FAANGWgsSetQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[FAANGWgsSetResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: MetagenomeAnalysisQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[MetagenomeAnalysisResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: MetagenomeAnalysisStudyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[MetagenomeAnalysisStudyResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: MetagenomeAssemblyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[MetagenomeAssemblyResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: MetagenomeCodingQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[MetagenomeCodingResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: MetagenomeNoncodingQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[MetagenomeNoncodingResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: MetagenomeReadExperimentQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[MetagenomeReadExperimentResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: MetagenomeReadRunQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[MetagenomeReadRunResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: MetagenomeReadStudyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[MetagenomeReadStudyResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: MetagenomeSampleQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[MetagenomeSampleResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: MetagenomeSequenceQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[MetagenomeSequenceResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: MetagenomeStudyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[MetagenomeStudyResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: MetagenomeTaxonQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[MetagenomeTaxonResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: MetagenomeTlsSetQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[MetagenomeTlsSetResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: MetagenomeTsaSetQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[MetagenomeTsaSetResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: MetagenomeWgsSetQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[MetagenomeWgsSetResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: PathogenAnalysisQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[PathogenAnalysisResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: PathogenAnalysisStudyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[PathogenAnalysisStudyResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: PathogenAssemblyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[PathogenAssemblyResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: PathogenCodingQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[PathogenCodingResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: PathogenNoncodingQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[PathogenNoncodingResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: PathogenReadExperimentQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[PathogenReadExperimentResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: PathogenReadRunQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[PathogenReadRunResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: PathogenReadStudyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[PathogenReadStudyResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: PathogenSampleQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[PathogenSampleResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: PathogenSequenceQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[PathogenSequenceResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: PathogenStudyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[PathogenStudyResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: PathogenTaxonQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[PathogenTaxonResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: PathogenTlsSetQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[PathogenTlsSetResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: PathogenTsaSetQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[PathogenTsaSetResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: PathogenWgsSetQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[PathogenWgsSetResult]: ...
    @overload
    def search(
        self,
        result: Enum,
        query: ENABaseQuery | ENAQueryClause,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[BaseModel]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: ENAAnalysisQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[ENAAnalysisResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: ENAAnalysisStudyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[ENAAnalysisStudyResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: ENAAssemblyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[ENAAssemblyResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: ENACodingQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[ENACodingResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: ENANoncodingQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[ENANoncodingResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: ENAReadExperimentQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[ENAReadExperimentResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: ENAReadRunQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[ENAReadRunResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: ENAReadStudyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[ENAReadStudyResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: ENASampleQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[ENASampleResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: ENASequenceQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[ENASequenceResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: ENAStudyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[ENAStudyResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: ENATaxonQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[ENATaxonResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: ENATlsSetQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[ENATlsSetResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: ENATsaSetQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[ENATsaSetResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: ENAWgsSetQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[ENAWgsSetResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: FAANGAnalysisQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[FAANGAnalysisResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: FAANGAnalysisStudyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[FAANGAnalysisStudyResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: FAANGAssemblyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[FAANGAssemblyResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: FAANGCodingQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[FAANGCodingResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: FAANGNoncodingQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[FAANGNoncodingResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: FAANGReadExperimentQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[FAANGReadExperimentResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: FAANGReadRunQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[FAANGReadRunResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: FAANGReadStudyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[FAANGReadStudyResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: FAANGSampleQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[FAANGSampleResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: FAANGSequenceQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[FAANGSequenceResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: FAANGStudyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[FAANGStudyResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: FAANGTaxonQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[FAANGTaxonResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: FAANGTlsSetQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[FAANGTlsSetResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: FAANGTsaSetQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[FAANGTsaSetResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: FAANGWgsSetQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[FAANGWgsSetResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: MetagenomeAnalysisQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[MetagenomeAnalysisResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: MetagenomeAnalysisStudyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[MetagenomeAnalysisStudyResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: MetagenomeAssemblyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[MetagenomeAssemblyResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: MetagenomeCodingQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[MetagenomeCodingResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: MetagenomeNoncodingQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[MetagenomeNoncodingResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: MetagenomeReadExperimentQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[MetagenomeReadExperimentResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: MetagenomeReadRunQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[MetagenomeReadRunResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: MetagenomeReadStudyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[MetagenomeReadStudyResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: MetagenomeSampleQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[MetagenomeSampleResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: MetagenomeSequenceQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[MetagenomeSequenceResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: MetagenomeStudyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[MetagenomeStudyResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: MetagenomeTaxonQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[MetagenomeTaxonResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: MetagenomeTlsSetQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[MetagenomeTlsSetResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: MetagenomeTsaSetQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[MetagenomeTsaSetResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: MetagenomeWgsSetQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[MetagenomeWgsSetResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: PathogenAnalysisQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[PathogenAnalysisResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: PathogenAnalysisStudyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[PathogenAnalysisStudyResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: PathogenAssemblyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[PathogenAssemblyResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: PathogenCodingQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[PathogenCodingResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: PathogenNoncodingQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[PathogenNoncodingResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: PathogenReadExperimentQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[PathogenReadExperimentResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: PathogenReadRunQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[PathogenReadRunResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: PathogenReadStudyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[PathogenReadStudyResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: PathogenSampleQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[PathogenSampleResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: PathogenSequenceQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[PathogenSequenceResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: PathogenStudyQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[PathogenStudyResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: PathogenTaxonQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[PathogenTaxonResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: PathogenTlsSetQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[PathogenTlsSetResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: PathogenTsaSetQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[PathogenTsaSetResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: PathogenWgsSetQuery,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[PathogenWgsSetResult]: ...
    @overload
    async def search_async(
        self,
        result: Enum,
        query: ENABaseQuery | ENAQueryClause,
        fields: list[Enum | str] | None = ...,
        portals: list[ENAPortalDataPortal] | tuple[ENAPortalDataPortal, ...] = ...,
        limit: int | None = ...,
        include_metagenomes: bool = ...,
        raise_on_empty: bool = ...,
        field_coercions: dict | None = ...,
        field_aliases: dict[str, str] | None = ...,
        exclude: dict[str, Any] | None = ...,
        auth: httpx.Auth | None = ...,
    ) -> list[BaseModel]: ...
    def get_study(
        self,
        primary_accession: str | None = ...,
        secondary_accession: str | None = ...,
        fields: list[Enum | str] | None = ...,
    ) -> (
        MetagenomeReadStudyResult
        | ENAReadStudyResult
        | MetagenomeAnalysisStudyResult
        | ENAAnalysisStudyResult
        | MetagenomeStudyResult
        | ENAStudyResult
        | None
    ): ...
    def get_sample(
        self,
        sample_accession: str,
        fields: list[Enum | str] | None = ...,
    ) -> MetagenomeSampleResult | ENASampleResult | None: ...
    def get_run(
        self,
        run_accession: str,
        fields: list[Enum | str] | None = ...,
    ) -> MetagenomeReadRunResult | ENAReadRunResult | None: ...
    def get_study_runs(
        self,
        study_accession: str,
        fields: list[Enum | str] | None = ...,
        filter_assembly_runs: bool = ...,
        filter_accessions: list[str] | None = ...,
    ) -> list[MetagenomeReadRunResult | ENAReadRunResult]: ...
    def get_study_assemblies(
        self,
        study_accession: str,
        fields: list[Enum | str] | None = ...,
        filter_accessions: list[str] | None = ...,
        allow_non_primary_assembly: bool = ...,
    ) -> list[MetagenomeAnalysisResult | ENAAnalysisResult]: ...
    def get_assembly(
        self,
        assembly_accession: str,
        fields: list[Enum | str] | None = ...,
    ) -> MetagenomeAnalysisResult | ENAAnalysisResult | None: ...
    def get_assembly_from_sample(
        self,
        sample_name: str,
        fields: list[Enum | str] | None = ...,
    ) -> MetagenomeAnalysisResult | ENAAnalysisResult | None: ...
    def get_updated_studies(
        self,
        cutoff_date: str,
        fields: list[Enum | str] | None = ...,
    ) -> list[MetagenomeStudyResult | ENAStudyResult]: ...
    def get_updated_runs(
        self,
        cutoff_date: str,
        fields: list[Enum | str] | None = ...,
    ) -> list[MetagenomeReadRunResult | ENAReadRunResult]: ...
    def get_updated_assemblies(
        self,
        cutoff_date: str,
        fields: list[Enum | str] | None = ...,
    ) -> list[MetagenomeAnalysisResult | ENAAnalysisResult]: ...
    def get_updated_tpa_assemblies(
        self,
        cutoff_date: str,
        fields: list[Enum | str] | None = ...,
    ) -> list[MetagenomeAnalysisResult | ENAAnalysisResult]: ...
    async def get_study_async(
        self,
        primary_accession: str | None = ...,
        secondary_accession: str | None = ...,
        fields: list[Enum | str] | None = ...,
    ) -> (
        MetagenomeReadStudyResult
        | ENAReadStudyResult
        | MetagenomeAnalysisStudyResult
        | ENAAnalysisStudyResult
        | MetagenomeStudyResult
        | ENAStudyResult
        | None
    ): ...
    async def get_sample_async(
        self,
        sample_accession: str,
        fields: list[Enum | str] | None = ...,
    ) -> MetagenomeSampleResult | ENASampleResult | None: ...
    async def get_run_async(
        self,
        run_accession: str,
        fields: list[Enum | str] | None = ...,
    ) -> MetagenomeReadRunResult | ENAReadRunResult | None: ...
    async def get_study_runs_async(
        self,
        study_accession: str,
        fields: list[Enum | str] | None = ...,
        filter_assembly_runs: bool = ...,
        filter_accessions: list[str] | None = ...,
    ) -> list[MetagenomeReadRunResult | ENAReadRunResult]: ...
    async def get_study_assemblies_async(
        self,
        study_accession: str,
        fields: list[Enum | str] | None = ...,
        filter_accessions: list[str] | None = ...,
        allow_non_primary_assembly: bool = ...,
    ) -> list[MetagenomeAnalysisResult | ENAAnalysisResult]: ...
    async def get_assembly_async(
        self,
        assembly_accession: str,
        fields: list[Enum | str] | None = ...,
    ) -> MetagenomeAnalysisResult | ENAAnalysisResult | None: ...
    async def get_assembly_from_sample_async(
        self,
        sample_name: str,
        fields: list[Enum | str] | None = ...,
    ) -> MetagenomeAnalysisResult | ENAAnalysisResult | None: ...
    async def get_updated_studies_async(
        self,
        cutoff_date: str,
        fields: list[Enum | str] | None = ...,
    ) -> list[MetagenomeStudyResult | ENAStudyResult]: ...
    async def get_updated_runs_async(
        self,
        cutoff_date: str,
        fields: list[Enum | str] | None = ...,
    ) -> list[MetagenomeReadRunResult | ENAReadRunResult]: ...
    async def get_updated_assemblies_async(
        self,
        cutoff_date: str,
        fields: list[Enum | str] | None = ...,
    ) -> list[MetagenomeAnalysisResult | ENAAnalysisResult]: ...
    async def get_updated_tpa_assemblies_async(
        self,
        cutoff_date: str,
        fields: list[Enum | str] | None = ...,
    ) -> list[MetagenomeAnalysisResult | ENAAnalysisResult]: ...
