# AUTO-GENERATED by scripts/generate_models.py — do not edit manually.
from __future__ import annotations

from .analysis import (
    MetagenomeAnalysisFields,
    MetagenomeAnalysisQuery,
    MetagenomeAnalysisResult,
)
from .analysis_study import (
    MetagenomeAnalysisStudyFields,
    MetagenomeAnalysisStudyQuery,
    MetagenomeAnalysisStudyResult,
)
from .assembly import (
    MetagenomeAssemblyFields,
    MetagenomeAssemblyQuery,
    MetagenomeAssemblyResult,
)
from .coding import (
    MetagenomeCodingFields,
    MetagenomeCodingQuery,
    MetagenomeCodingResult,
)
from .noncoding import (
    MetagenomeNoncodingFields,
    MetagenomeNoncodingQuery,
    MetagenomeNoncodingResult,
)
from .read_experiment import (
    MetagenomeReadExperimentFields,
    MetagenomeReadExperimentQuery,
    MetagenomeReadExperimentResult,
)
from .read_run import (
    MetagenomeReadRunFields,
    MetagenomeReadRunQuery,
    MetagenomeReadRunResult,
)
from .read_study import (
    MetagenomeReadStudyFields,
    MetagenomeReadStudyQuery,
    MetagenomeReadStudyResult,
)
from .sample import (
    MetagenomeSampleFields,
    MetagenomeSampleQuery,
    MetagenomeSampleResult,
)
from .sequence import (
    MetagenomeSequenceFields,
    MetagenomeSequenceQuery,
    MetagenomeSequenceResult,
)
from .study import MetagenomeStudyFields, MetagenomeStudyQuery, MetagenomeStudyResult
from .taxon import MetagenomeTaxonFields, MetagenomeTaxonQuery, MetagenomeTaxonResult
from .tls_set import (
    MetagenomeTlsSetFields,
    MetagenomeTlsSetQuery,
    MetagenomeTlsSetResult,
)
from .tsa_set import (
    MetagenomeTsaSetFields,
    MetagenomeTsaSetQuery,
    MetagenomeTsaSetResult,
)
from .wgs_set import (
    MetagenomeWgsSetFields,
    MetagenomeWgsSetQuery,
    MetagenomeWgsSetResult,
)

__all__ = [
    "MetagenomeAnalysisFields",
    "MetagenomeAnalysisQuery",
    "MetagenomeAnalysisResult",
    "MetagenomeAnalysisStudyFields",
    "MetagenomeAnalysisStudyQuery",
    "MetagenomeAnalysisStudyResult",
    "MetagenomeAssemblyFields",
    "MetagenomeAssemblyQuery",
    "MetagenomeAssemblyResult",
    "MetagenomeCodingFields",
    "MetagenomeCodingQuery",
    "MetagenomeCodingResult",
    "MetagenomeNoncodingFields",
    "MetagenomeNoncodingQuery",
    "MetagenomeNoncodingResult",
    "MetagenomeReadExperimentFields",
    "MetagenomeReadExperimentQuery",
    "MetagenomeReadExperimentResult",
    "MetagenomeReadRunFields",
    "MetagenomeReadRunQuery",
    "MetagenomeReadRunResult",
    "MetagenomeReadStudyFields",
    "MetagenomeReadStudyQuery",
    "MetagenomeReadStudyResult",
    "MetagenomeSampleFields",
    "MetagenomeSampleQuery",
    "MetagenomeSampleResult",
    "MetagenomeSequenceFields",
    "MetagenomeSequenceQuery",
    "MetagenomeSequenceResult",
    "MetagenomeStudyFields",
    "MetagenomeStudyQuery",
    "MetagenomeStudyResult",
    "MetagenomeTaxonFields",
    "MetagenomeTaxonQuery",
    "MetagenomeTaxonResult",
    "MetagenomeTlsSetFields",
    "MetagenomeTlsSetQuery",
    "MetagenomeTlsSetResult",
    "MetagenomeTsaSetFields",
    "MetagenomeTsaSetQuery",
    "MetagenomeTsaSetResult",
    "MetagenomeWgsSetFields",
    "MetagenomeWgsSetQuery",
    "MetagenomeWgsSetResult",
]
