# AUTO-GENERATED by scripts/generate_models.py — do not edit manually.
# Portal: metagenome | Result type: noncoding
from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field

from ena_api_handler.query import ENABaseQuery


class MetagenomeNoncodingFields(str, Enum):
    """Returnable fields for noncoding via the metagenome portal."""

    ACCESSION = "accession"  # accession number
    ALTITUDE = "altitude"  # Altitude (m)
    ANTICODON = "anticodon"  # location of the anticodon of tRNA and the amino acid for which it codes
    BASE_COUNT = "base_count"  # number of base pairs
    BIO_MATERIAL = "bio_material"  # identifier for biological material including institute and collection code
    CELL_LINE = "cell_line"  # cell line from which the sample was obtained
    CELL_TYPE = "cell_type"  # cell type from which the sample was obtained
    COLLECTED_BY = "collected_by"  # name of the person who collected the specimen
    COLLECTION_DATE = "collection_date"  # Time when specimen was collected
    COLLECTION_DATE_END = "collection_date_end"  # Time when specimen was collected
    COLLECTION_DATE_START = "collection_date_start"  # Time when specimen was collected
    COUNTRY = "country"  # locality of sample isolation: country names, oceans or seas, followed by regions and localities
    CULTIVAR = "cultivar"  # cultivar (cultivated variety) of plant from which sample was obtained
    CULTURE_COLLECTION = "culture_collection"  # identifier for the sample culture including institute and collection code
    DATACLASS = "dataclass"  # sequence data class
    DESCRIPTION = "description"  # brief sequence description
    DEV_STAGE = "dev_stage"  # sample obtained from an organism in a specific developmental stage
    ECOTYPE = "ecotype"  # a population within a given species displaying traits that reflect adaptation to a local habitat
    ENVIRONMENTAL_SAMPLE = "environmental_sample"  # identifies sequences derived by direct molecular isolation from an environmental DNA sample
    EXPERIMENT = (
        "experiment"  # a brief description of the nature of the experimental evidence
    )
    FIRST_PUBLIC = "first_public"  # date when made public
    FUNCTION = "function"  # function attributed to a sequence
    GENE = "gene"  # symbol of the gene corresponding to a sequence region
    GENE_SYNONYM = (
        "gene_synonym"  # synonymous, replaced, obsolete or former gene symbol
    )
    GERMLINE = "germline"  # the sample is an unrearranged molecule that was inherited from the parental germline
    HAPLOTYPE = "haplotype"  # combination of alleles that are linked together on the same physical chromosome
    HOST = "host"  # natural (as opposed to laboratory) host to the organism from which sample was obtained
    IDENTIFIED_BY = (
        "identified_by"  # name of the taxonomist who identified the specimen
    )
    INDEXED_DATE = "indexed_date"  # date when record was indexed for presentation
    INFERENCE = "inference"  # a structured description of non-experimental evidence
    ISOLATE = "isolate"  # individual isolate from which sample was obtained
    ISOLATION_SOURCE = "isolation_source"  # describes the physical, environmental and/or local geographical source of the sample
    KEYWORDS = "keywords"  # keywords associated with sequence
    LAB_HOST = "lab_host"  # scientific name of the laboratory host used to propagate the source organism for the sample
    LAST_UPDATED = "last_updated"  # date when last updated
    LOCATION = "location"  # geographic location of isolation of the sample
    LOCUS_TAG = "locus_tag"  # a submitter-supplied, systematic, stable identifier for a gene and its associated features
    MARKER = "marker"  # marker classification
    MATING_TYPE = "mating_type"  # mating type of the organism from which the sequence was obtained
    MOL_TYPE = "mol_type"  # in vivo molecule type of the sequence
    ORGANELLE = "organelle"  # membrane-bound intracellular structure from which the sequence was obtained
    PARENT_ACCESSION = "parent_accession"  # parent sequence accession number
    PLASMID = "plasmid"  # name of naturally occurring plasmid from which the sequence was obtained
    PRODUCT = "product"  # name of the product associated with the feature
    RNA_CLASS = "rna_class"  # classification of RNA
    SAMPLE_ACCESSION = "sample_accession"  # sample accession number
    SCIENTIFIC_NAME = "scientific_name"  # scientific name of an organism
    SEQUENCE_MD5 = "sequence_md5"  # MD5 checksum of sequence
    SEQUENCE_VERSION = "sequence_version"  # Version of the sequence
    SEROTYPE = "serotype"  # serological variety of a species characterized by its antigenic properties
    SEROVAR = "serovar"  # serological variety of a species (usually a prokaryote) characterized by its antigenic properties
    SEX = "sex"  # sex of the organism from which the sample was obtained
    SPECIMEN_VOUCHER = "specimen_voucher"  # identifier for the sample culture including institute and collection code
    STATUS = "status"  # Status
    STRAIN = "strain"  # strain from which sample was obtained
    STUDY_ACCESSION = "study_accession"  # study accession number
    SUB_SPECIES = (
        "sub_species"  # name of sub-species of organism from which sample was obtained
    )
    SUB_STRAIN = "sub_strain"  # name or identifier of a genetically or otherwise modified strain from which sample was obtained
    TAG = "tag"  # Classification Tags
    TAX_DIVISION = "tax_division"  # taxonomic division
    TAX_ID = "tax_id"  # NCBI taxonomic classification
    TAX_LINEAGE = "tax_lineage"  # Complete taxonomic lineage for an organism
    TISSUE_LIB = "tissue_lib"  # tissue library from which sample was obtained
    TISSUE_TYPE = "tissue_type"  # tissue type from which the sample was obtained
    TOPOLOGY = "topology"  # sequence topology: circular or linear
    VARIETY = "variety"  # variety (varietas, a formal Linnaean rank) of organism from which sample was derived


class MetagenomeNoncodingQuery(ENABaseQuery):
    """Searchable fields for noncoding via the metagenome portal."""

    accession: Optional[str] = Field(default=None, description="accession number")
    altitude: Optional[str] = Field(default=None, description="Altitude (m)")
    anticodon: Optional[str] = Field(
        default=None,
        description="location of the anticodon of tRNA and the amino acid for which it codes",
    )
    base_count: Optional[str] = Field(default=None, description="number of base pairs")
    bio_material: Optional[str] = Field(
        default=None,
        description="identifier for biological material including institute and collection code",
    )
    cell_line: Optional[str] = Field(
        default=None, description="cell line from which the sample was obtained"
    )
    cell_type: Optional[str] = Field(
        default=None, description="cell type from which the sample was obtained"
    )
    collected_by: Optional[str] = Field(
        default=None, description="name of the person who collected the specimen"
    )
    country: Optional[str] = Field(
        default=None,
        description="locality of sample isolation: country names, oceans or seas, followed by regions and localities",
    )
    cultivar: Optional[str] = Field(
        default=None,
        description="cultivar (cultivated variety) of plant from which sample was obtained",
    )
    culture_collection: Optional[str] = Field(
        default=None,
        description="identifier for the sample culture including institute and collection code",
    )
    dataclass: Optional[str] = Field(default=None, description="sequence data class")
    description: Optional[str] = Field(
        default=None, description="brief sequence description"
    )
    dev_stage: Optional[str] = Field(
        default=None,
        description="sample obtained from an organism in a specific developmental stage",
    )
    ecotype: Optional[str] = Field(
        default=None,
        description="a population within a given species displaying traits that reflect adaptation to a local habitat",
    )
    environmental_sample: Optional[bool] = Field(
        default=None,
        description="identifies sequences derived by direct molecular isolation from an environmental DNA sample",
    )
    experiment: Optional[str] = Field(
        default=None,
        description="a brief description of the nature of the experimental evidence",
    )
    first_public: Optional[str] = Field(
        default=None, description="date when made public"
    )
    function: Optional[str] = Field(
        default=None, description="function attributed to a sequence"
    )
    gene: Optional[str] = Field(
        default=None,
        description="symbol of the gene corresponding to a sequence region",
    )
    gene_synonym: Optional[str] = Field(
        default=None, description="synonymous, replaced, obsolete or former gene symbol"
    )
    germline: Optional[bool] = Field(
        default=None,
        description="the sample is an unrearranged molecule that was inherited from the parental germline",
    )
    haplotype: Optional[str] = Field(
        default=None,
        description="combination of alleles that are linked together on the same physical chromosome",
    )
    host: Optional[str] = Field(
        default=None,
        description="natural (as opposed to laboratory) host to the organism from which sample was obtained",
    )
    identified_by: Optional[str] = Field(
        default=None, description="name of the taxonomist who identified the specimen"
    )
    indexed_date: Optional[str] = Field(
        default=None, description="date when record was indexed for presentation"
    )
    inference: Optional[str] = Field(
        default=None,
        description="a structured description of non-experimental evidence",
    )
    isolate: Optional[str] = Field(
        default=None, description="individual isolate from which sample was obtained"
    )
    isolation_source: Optional[str] = Field(
        default=None,
        description="describes the physical, environmental and/or local geographical source of the sample",
    )
    keywords: Optional[str] = Field(
        default=None, description="keywords associated with sequence"
    )
    lab_host: Optional[str] = Field(
        default=None,
        description="scientific name of the laboratory host used to propagate the source organism for the sample",
    )
    last_updated: Optional[str] = Field(
        default=None, description="date when last updated"
    )
    location: Optional[str] = Field(
        default=None, description="geographic location of isolation of the sample"
    )
    locus_tag: Optional[str] = Field(
        default=None,
        description="a submitter-supplied, systematic, stable identifier for a gene and its associated features",
    )
    marker: Optional[str] = Field(default=None, description="marker classification")
    mating_type: Optional[str] = Field(
        default=None,
        description="mating type of the organism from which the sequence was obtained",
    )
    mol_type: Optional[str] = Field(
        default=None, description="in vivo molecule type of the sequence"
    )
    organelle: Optional[str] = Field(
        default=None,
        description="membrane-bound intracellular structure from which the sequence was obtained",
    )
    parent_accession: Optional[str] = Field(
        default=None, description="parent sequence accession number"
    )
    plasmid: Optional[str] = Field(
        default=None,
        description="name of naturally occurring plasmid from which the sequence was obtained",
    )
    product: Optional[str] = Field(
        default=None, description="name of the product associated with the feature"
    )
    rna_class: Optional[str] = Field(default=None, description="classification of RNA")
    sample_accession: Optional[str] = Field(
        default=None, description="sample accession number"
    )
    scientific_name: Optional[str] = Field(
        default=None, description="scientific name of an organism"
    )
    sequence_md5: Optional[str] = Field(
        default=None, description="MD5 checksum of sequence"
    )
    sequence_version: Optional[str] = Field(
        default=None, description="Version of the sequence"
    )
    serotype: Optional[str] = Field(
        default=None,
        description="serological variety of a species characterized by its antigenic properties",
    )
    serovar: Optional[str] = Field(
        default=None,
        description="serological variety of a species (usually a prokaryote) characterized by its antigenic properties",
    )
    sex: Optional[str] = Field(
        default=None,
        description="sex of the organism from which the sample was obtained",
    )
    specimen_voucher: Optional[str] = Field(
        default=None,
        description="identifier for the sample culture including institute and collection code",
    )
    status: Optional[str] = Field(default=None, description="Status")
    strain: Optional[str] = Field(
        default=None, description="strain from which sample was obtained"
    )
    study_accession: Optional[str] = Field(
        default=None, description="study accession number"
    )
    sub_species: Optional[str] = Field(
        default=None,
        description="name of sub-species of organism from which sample was obtained",
    )
    sub_strain: Optional[str] = Field(
        default=None,
        description="name or identifier of a genetically or otherwise modified strain from which sample was obtained",
    )
    tag: Optional[str] = Field(default=None, description="Classification Tags")
    tax_division: Optional[str] = Field(default=None, description="taxonomic division")
    tax_id: Optional[str] = Field(
        default=None, description="NCBI taxonomic classification"
    )
    tissue_lib: Optional[str] = Field(
        default=None, description="tissue library from which sample was obtained"
    )
    tissue_type: Optional[str] = Field(
        default=None, description="tissue type from which the sample was obtained"
    )
    topology: Optional[str] = Field(
        default=None, description="sequence topology: circular or linear"
    )
    variety: Optional[str] = Field(
        default=None,
        description="variety (varietas, a formal Linnaean rank) of organism from which sample was derived",
    )


class MetagenomeNoncodingResult(BaseModel):
    """Typed result row for noncoding via the metagenome portal."""

    model_config = ConfigDict(extra="allow")

    accession: Optional[str] = Field(default=None, description="accession number")
    altitude: Optional[str] = Field(default=None, description="Altitude (m)")
    anticodon: Optional[str] = Field(
        default=None,
        description="location of the anticodon of tRNA and the amino acid for which it codes",
    )
    base_count: Optional[str] = Field(default=None, description="number of base pairs")
    bio_material: Optional[str] = Field(
        default=None,
        description="identifier for biological material including institute and collection code",
    )
    cell_line: Optional[str] = Field(
        default=None, description="cell line from which the sample was obtained"
    )
    cell_type: Optional[str] = Field(
        default=None, description="cell type from which the sample was obtained"
    )
    collected_by: Optional[str] = Field(
        default=None, description="name of the person who collected the specimen"
    )
    collection_date: Optional[str] = Field(
        default=None, description="Time when specimen was collected"
    )
    collection_date_end: Optional[str] = Field(
        default=None, description="Time when specimen was collected"
    )
    collection_date_start: Optional[str] = Field(
        default=None, description="Time when specimen was collected"
    )
    country: Optional[str] = Field(
        default=None,
        description="locality of sample isolation: country names, oceans or seas, followed by regions and localities",
    )
    cultivar: Optional[str] = Field(
        default=None,
        description="cultivar (cultivated variety) of plant from which sample was obtained",
    )
    culture_collection: Optional[str] = Field(
        default=None,
        description="identifier for the sample culture including institute and collection code",
    )
    dataclass: Optional[str] = Field(default=None, description="sequence data class")
    description: Optional[str] = Field(
        default=None, description="brief sequence description"
    )
    dev_stage: Optional[str] = Field(
        default=None,
        description="sample obtained from an organism in a specific developmental stage",
    )
    ecotype: Optional[str] = Field(
        default=None,
        description="a population within a given species displaying traits that reflect adaptation to a local habitat",
    )
    environmental_sample: Optional[bool] = Field(
        default=None,
        description="identifies sequences derived by direct molecular isolation from an environmental DNA sample",
    )
    experiment: Optional[str] = Field(
        default=None,
        description="a brief description of the nature of the experimental evidence",
    )
    first_public: Optional[str] = Field(
        default=None, description="date when made public"
    )
    function: Optional[str] = Field(
        default=None, description="function attributed to a sequence"
    )
    gene: Optional[str] = Field(
        default=None,
        description="symbol of the gene corresponding to a sequence region",
    )
    gene_synonym: Optional[str] = Field(
        default=None, description="synonymous, replaced, obsolete or former gene symbol"
    )
    germline: Optional[bool] = Field(
        default=None,
        description="the sample is an unrearranged molecule that was inherited from the parental germline",
    )
    haplotype: Optional[str] = Field(
        default=None,
        description="combination of alleles that are linked together on the same physical chromosome",
    )
    host: Optional[str] = Field(
        default=None,
        description="natural (as opposed to laboratory) host to the organism from which sample was obtained",
    )
    identified_by: Optional[str] = Field(
        default=None, description="name of the taxonomist who identified the specimen"
    )
    indexed_date: Optional[str] = Field(
        default=None, description="date when record was indexed for presentation"
    )
    inference: Optional[str] = Field(
        default=None,
        description="a structured description of non-experimental evidence",
    )
    isolate: Optional[str] = Field(
        default=None, description="individual isolate from which sample was obtained"
    )
    isolation_source: Optional[str] = Field(
        default=None,
        description="describes the physical, environmental and/or local geographical source of the sample",
    )
    keywords: Optional[str] = Field(
        default=None, description="keywords associated with sequence"
    )
    lab_host: Optional[str] = Field(
        default=None,
        description="scientific name of the laboratory host used to propagate the source organism for the sample",
    )
    last_updated: Optional[str] = Field(
        default=None, description="date when last updated"
    )
    location: Optional[str] = Field(
        default=None, description="geographic location of isolation of the sample"
    )
    locus_tag: Optional[str] = Field(
        default=None,
        description="a submitter-supplied, systematic, stable identifier for a gene and its associated features",
    )
    marker: Optional[str] = Field(default=None, description="marker classification")
    mating_type: Optional[str] = Field(
        default=None,
        description="mating type of the organism from which the sequence was obtained",
    )
    mol_type: Optional[str] = Field(
        default=None, description="in vivo molecule type of the sequence"
    )
    organelle: Optional[str] = Field(
        default=None,
        description="membrane-bound intracellular structure from which the sequence was obtained",
    )
    parent_accession: Optional[str] = Field(
        default=None, description="parent sequence accession number"
    )
    plasmid: Optional[str] = Field(
        default=None,
        description="name of naturally occurring plasmid from which the sequence was obtained",
    )
    product: Optional[str] = Field(
        default=None, description="name of the product associated with the feature"
    )
    rna_class: Optional[str] = Field(default=None, description="classification of RNA")
    sample_accession: Optional[str] = Field(
        default=None, description="sample accession number"
    )
    scientific_name: Optional[str] = Field(
        default=None, description="scientific name of an organism"
    )
    sequence_md5: Optional[str] = Field(
        default=None, description="MD5 checksum of sequence"
    )
    sequence_version: Optional[str] = Field(
        default=None, description="Version of the sequence"
    )
    serotype: Optional[str] = Field(
        default=None,
        description="serological variety of a species characterized by its antigenic properties",
    )
    serovar: Optional[str] = Field(
        default=None,
        description="serological variety of a species (usually a prokaryote) characterized by its antigenic properties",
    )
    sex: Optional[str] = Field(
        default=None,
        description="sex of the organism from which the sample was obtained",
    )
    specimen_voucher: Optional[str] = Field(
        default=None,
        description="identifier for the sample culture including institute and collection code",
    )
    status: Optional[str] = Field(default=None, description="Status")
    strain: Optional[str] = Field(
        default=None, description="strain from which sample was obtained"
    )
    study_accession: Optional[str] = Field(
        default=None, description="study accession number"
    )
    sub_species: Optional[str] = Field(
        default=None,
        description="name of sub-species of organism from which sample was obtained",
    )
    sub_strain: Optional[str] = Field(
        default=None,
        description="name or identifier of a genetically or otherwise modified strain from which sample was obtained",
    )
    tag: Optional[str] = Field(default=None, description="Classification Tags")
    tax_division: Optional[str] = Field(default=None, description="taxonomic division")
    tax_id: Optional[str] = Field(
        default=None, description="NCBI taxonomic classification"
    )
    tax_lineage: Optional[str] = Field(
        default=None, description="Complete taxonomic lineage for an organism"
    )
    tissue_lib: Optional[str] = Field(
        default=None, description="tissue library from which sample was obtained"
    )
    tissue_type: Optional[str] = Field(
        default=None, description="tissue type from which the sample was obtained"
    )
    topology: Optional[str] = Field(
        default=None, description="sequence topology: circular or linear"
    )
    variety: Optional[str] = Field(
        default=None,
        description="variety (varietas, a formal Linnaean rank) of organism from which sample was derived",
    )
